export enum TEST_ID {
  LOGIN_BUTTON = "login-button",
  SIGNUP_BUTTON = "signup-button",
  MOVE_TO_SIGN_UP_BUTTON = "move-to-signup-button",
  LINE_ADD_BUTTON = "line-add-button",
  LINE_NAME_INPUT = "line-name-add-button",
  LINE_UP_STATION_SELECT = "line-up-station-select",
  LINE_DOWN_STATION_SELECT = "line-down-station-select",
  LINE_DISTANCE_INPUT = "line-distance-input",
  SECTION_MODAL = "section-modal",
  SECTION_MODAL_OPEN_BUTTON = "section-modal-open-button",
  SECTION_ADD_BUTTON = "section-add-button",
  SECTION_UP_STATION_SELECT = "section-up-station-select",
  SECTION_DOWN_STATION_SELECT = "section-down-station-select",
  SECTION_DISTANCE_INPUT = "section-distance-input",
}
