export const STATION = {
  NAME_MIN_LENGTH: 2,
  NAME_MAX_LENGTH: 20,
};

export const LINE = {
  NAME_MIN_LENGTH: 2,
  NAME_MAX_LENGTH: 10,
  MIN_QUANTITY_STATION_TO_ADD_LINE: 2,
};

export const SECTION = {
  MIN_QUANTITY_STATION_TO_DELETE_SECTION: 3,
};
