const ERROR_TYPE = {
  DEFAULT: 'DEFAULT',
  UNAUTHORIZED: 'UNAUTHORIZED',
  INVALID_LOGIN_INFO: 'INVALID_LOGIN_INFO',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  DUPLICATED: 'DUPLICATED',
  NO_ACCESS_TOKEN: 'NO_ACCESS_TOKEN',
  STATION_IN_SECTION: 'STATION_IN_SECTION',
};

export default ERROR_TYPE;
