const ERROR_TYPE: { [key: string]: string } = {
  '500': 'INTERNAL_SERVER_ERROR',
  '400': 'BAD_REQUEST',
  '401': 'UNAUTHORIZED',
  BAD_REQUEST: 'BAD_REQUEST',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  DEFAULT: 'DEFAULT',
  UNAUTHORIZED: 'UNAUTHORIZED',
  INVALID_LOGIN_INFO: 'INVALID_LOGIN_INFO',
  DUPLICATED: 'DUPLICATED',
  NO_ACCESS_TOKEN: 'NO_ACCESS_TOKEN',
  STATION_IN_SECTION: 'STATION_IN_SECTION',
  SECTION_LENGTH_OUT_OF_RANGE: 'SECTION_LENGTH_OUT_OF_RANGE',
};

export default ERROR_TYPE;
