const ERROR_TYPE: { [key: string]: string } = {
  '500': 'INTERNAL_SERVER_ERROR',
  '400': 'BAD_REQUEST',
  '401': 'UNAUTHORIZED',
  BAD_REQUEST: 'BAD_REQUEST',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  DEFAULT: 'DEFAULT',
};

export default ERROR_TYPE;
