export const VALIDATION = {
  EMPTY_INPUT: ' ',
  MIN_AGE: 1,
  MAX_AGE: 200,
  MIN_DISTANCE: 1,
  MIN_PASSWORD_LENGTH: 4,
  MAX_PASSWORD_LENGTH: 20,
  MIN_STATION_NAME_LENGTH: 2,
  MAX_STATION_NAME_LENGTH: 20,
  MIN_LINE_NAME_LENGTH: 2,
  MAX_LINE_NAME_LENGTH: 10,
  MIN_NUM_OF_STATIONS_IN_LINE: 2,
  LAST_STATION_DISTANCE: -1,
};
