const STATION_VALUE = {
  NAME_MIN_LENGTH: 2,
  NAME_MAX_LENGTH: 20,
};

const LINE_VALUE = {
  NAME_MIN_LENGTH: 2,
  NAME_MAX_LENGTH: 10,
  DISTANCE_MIN_VALUE: 1,
  DISTANCE_MAX_VALUE: 300,
};

const SECTION_VALUE = {
  DISTANCE_MIN_VALUE: 1,
  DISTANCE_MAX_VALUE: 300,
};

const SIGNUP_VALUE = {
  AGE_MIN_VALUE: 1,
  AGE_MAX_VALUE: 200,
  AGE_MAX_LENGTH: 3,
};

export { STATION_VALUE, LINE_VALUE, SECTION_VALUE, SIGNUP_VALUE };
